[package]
name = "core-wasm"
version = "1.0.0"
description = "Troopa core powered by WebAssembly."
edition = "2018"
license = "MIT"
repository = "https://github.com/hata6502/troopa-wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.7.2"
rand = "0.7.3"
wasm-bindgen = "0.2"
